global.User = require('./models/user')
global.Venue = require('./models/venue')
global.Event = require('./models/event')
global.Personal = require('./models/personal')
global.Venue = require('./models/venue')
